# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('LogOn', models.DateTimeField(null=True, verbose_name='Logon Current Session')),
                ('LogOff', models.DateTimeField(null=True, verbose_name='Logoff Current Session')),
                ('Host', models.CharField(max_length=64, verbose_name='Host name')),
                ('ipAddr', models.GenericIPAddressField(verbose_name='IP Address')),
                ('User', models.CharField(max_length=64, verbose_name='User Name')),
                ('Trust', models.BooleanField(default=True, verbose_name='Trust to current value')),
            ],
        ),
    ]
