# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login_name', models.CharField(max_length=32, unique=True, verbose_name='user login')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name User')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name User')),
                ('display_name', models.CharField(max_length=64, verbose_name='Display Name User')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email address')),
                ('title', models.CharField(default='Consultant ltd.', max_length=64, verbose_name='Organization Name (eg, company)')),
                ('departament', models.CharField(max_length=64, verbose_name='Organizational Unit Name (eg, section)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
